version: '3.8'

services:
  nginx1:
    image: nginx
    volumes:
      - ./index.1.html:/usr/share/nginx/html/index.html
    networks:
      net_go_app:
        ipv4_address: 10.100.17.2

  nginx2:
    image: nginx
    volumes:
      - ./index.2.html:/usr/share/nginx/html/index.html
    networks:
      net_go_app:
        ipv4_address: 10.100.17.3

  web-server-go1:
    image: web-server1
    ports:
      - "8080:3000"
    networks:
      net_go_app:
        ipv4_address: 10.100.17.4

  nginx4:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      net_go_app:
        ipv4_address: 10.100.17.5

networks:
  net_go_app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.100.17.0/24"
